# **(ADD THE NOTEBOOK NAME HERE)**

## Objectives

* Analyse online retail transaction data to understand customer behaviour, identify popular products, and optimise pricing and marketing strategies.

## Inputs

* data/source/online_retail.csv

## Outputs

* data/source/online_retail_cleaned.csv

## Additional Comments

* If you have any additional comments that don't fit in the previous bullets, please state them here.

---

# Change working directory

* We are assuming you will store the notebooks in a subfolder, therefore when running the notebook in the editor, you will need to change the working directory

We need to change the working directory from its current folder to its parent folder
* We access the current directory with os.getcwd()

In [2]:
import os
current_dir = os.getcwd()
current_dir

'/Users/tildeholmqvist/Documents/VS_Code_Tilde/DA_project_1/DA_project_1/jupyter_notebooks'

We want to make the parent of the current directory the new current directory
* os.path.dirname() gets the parent directory
* os.chir() defines the new current directory

In [3]:
os.chdir(os.path.dirname(current_dir))
print("You set a new current directory")

You set a new current directory

Confirm the new current directory

In [4]:
current_dir = os.getcwd()
current_dir

'/Users/tildeholmqvist/Documents/VS_Code_Tilde/DA_project_1/DA_project_1'

In [5]:
!pip install -r requirements.txt

Requirement already satisfied: numpy==1.26.1 in ./.venv/lib/python3.12/site-packages (from -r requirements.txt (line 1)) (1.26.1)
Requirement already satisfied: pandas==2.1.1 in ./.venv/lib/python3.12/site-packages (from -r requirements.txt (line 2)) (2.1.1)
Requirement already satisfied: matplotlib==3.8.0 in ./.venv/lib/python3.12/site-packages (from -r requirements.txt (line 3)) (3.8.0)
Requirement already satisfied: seaborn==0.13.2 in ./.venv/lib/python3.12/site-packages (from -r requirements.txt (line 4)) (0.13.2)
Requirement already satisfied: ydata-profiling==4.12.0 in ./.venv/lib/python3.12/site-packages (from -r requirements.txt (line 5)) (4.12.0)
Requirement already satisfied: plotly==5.17.0 in ./.venv/lib/python3.12/site-packages (from -r requirements.txt (line 6)) (5.17.0)
Requirement already satisfied: streamlit==1.40.2 in ./.venv/lib/python3.12/site-packages (from -r requirements.txt (line 7)) (1.40.2)
Requirement already satisfied: feature-engine==1.6.1 in ./.venv/lib/python3.12/site-packages (from -r requirements.txt (line 8)) (1.6.1)
Requirement already satisfied: imbalanced-learn==0.11.0 in ./.venv/lib/python3.12/site-packages (from -r requirements.txt (line 9)) (0.11.0)
Requirement already satisfied: scikit-learn==1.3.1 in ./.venv/lib/python3.12/site-packages (from -r requirements.txt (line 10)) (1.3.1)
Requirement already satisfied: xgboost==1.7.6 in ./.venv/lib/python3.12/site-packages (from -r requirements.txt (line 11)) (1.7.6)
Requirement already satisfied: yellowbrick==1.5 in ./.venv/lib/python3.12/site-packages (from -r requirements.txt (line 12)) (1.5)
Requirement already satisfied: Pillow==10.0.1 in ./.venv/lib/python3.12/site-packages (from -r requirements.txt (line 13)) (10.0.1)
Requirement already satisfied: openpyxl in ./.venv/lib/python3.12/site-packages (from -r requirements.txt (line 14)) (3.1.5)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.12/site-packages (from pandas==2.1.1->-r requirements.txt (line 2)) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in ./.venv/lib/python3.12/site-packages (from pandas==2.1.1->-r requirements.txt (line 2)) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.1 in ./.venv/lib/python3.12/site-packages (from pandas==2.1.1->-r requirements.txt (line 2)) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in ./.venv/lib/python3.12/site-packages (from matplotlib==3.8.0->-r requirements.txt (line 3)) (1.3.3)
Requirement already satisfied: cycler>=0.10 in ./.venv/lib/python3.12/site-packages (from matplotlib==3.8.0->-r requirements.txt (line 3)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in ./.venv/lib/python3.12/site-packages (from matplotlib==3.8.0->-r requirements.txt (line 3)) (4.62.1)
Requirement already satisfied: kiwisolver>=1.0.1 in ./.venv/lib/python3.12/site-packages (from matplotlib==3.8.0->-r requirements.txt (line 3)) (1.5.0)
Requirement already satisfied: packaging>=20.0 in ./.venv/lib/python3.12/site-packages (from matplotlib==3.8.0->-r requirements.txt (line 3)) (24.2)
Requirement already satisfied: pyparsing>=2.3.1 in ./.venv/lib/python3.12/site-packages (from matplotlib==3.8.0->-r requirements.txt (line 3)) (3.3.2)
Requirement already satisfied: scipy<1.14,>=1.4.1 in ./.venv/lib/python3.12/site-packages (from ydata-profiling==4.12.0->-r requirements.txt (line 5)) (1.13.1)
Requirement already satisfied: pydantic>=2 in ./.venv/lib/python3.12/site-packages (from ydata-profiling==4.12.0->-r requirements.txt (line 5)) (2.12.5)
Requirement already satisfied: PyYAML<6.1,>=5.0.0 in ./.venv/lib/python3.12/site-packages (from ydata-profiling==4.12.0->-r requirements.txt (line 5)) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=2.11.1 in ./.venv/lib/python3.12/site-packages (from ydata-profiling==4.12.0->-r requirements.txt (line 5)) (3.1.6)
Requirement already satisfied: visions<0.7.7,>=0.7.5 in ./.venv/lib/python3.12/site-packages (from visions[type_image_path]<0.7.7,>=0.7.5->ydata-profiling==4.12.0->-r requirements.txt (line 5)) (0.7.6)
Requirement already satisfied: htmlmin==0.1.12 in ./.venv/lib/python3.12/site-packages (from ydata-profiling==4.12.0->-r requirements.txt (line 5)) (0.1.12)
Requirement already satisfied: phik<0.13,>=0.11.1 in ./.venv/lib/python3.12/site-packages (from ydata-profiling==4.12.0->-r requirements.txt (line 5)) (0.12.5)
Requirement already satisfied: requests<3,>=2.24.0 in ./.venv/lib/python3.12/site-packages (from ydata-profiling==4.12.0->-r requirements.txt (line 5)) (2.32.5)
Requirement already satisfied: tqdm<5,>=4.48.2 in ./.venv/lib/python3.12/site-packages (from ydata-profiling==4.12.0->-r requirements.txt (line 5)) (4.67.3)
Requirement already satisfied: multimethod<2,>=1.4 in ./.venv/lib/python3.12/site-packages (from ydata-profiling==4.12.0->-r requirements.txt (line 5)) (1.12)
Requirement already satisfied: statsmodels<1,>=0.13.2 in ./.venv/lib/python3.12/site-packages (from ydata-profiling==4.12.0->-r requirements.txt (line 5)) (0.14.6)
Requirement already satisfied: typeguard<5,>=3 in ./.venv/lib/python3.12/site-packages (from ydata-profiling==4.12.0->-r requirements.txt (line 5)) (4.5.1)
Requirement already satisfied: imagehash==4.3.1 in ./.venv/lib/python3.12/site-packages (from ydata-profiling==4.12.0->-r requirements.txt (line 5)) (4.3.1)
Requirement already satisfied: wordcloud>=1.9.3 in ./.venv/lib/python3.12/site-packages (from ydata-profiling==4.12.0->-r requirements.txt (line 5)) (1.9.6)
Requirement already satisfied: dacite>=1.8 in ./.venv/lib/python3.12/site-packages (from ydata-profiling==4.12.0->-r requirements.txt (line 5)) (1.9.2)
Requirement already satisfied: numba<1,>=0.56.0 in ./.venv/lib/python3.12/site-packages (from ydata-profiling==4.12.0->-r requirements.txt (line 5)) (0.64.0)
Requirement already satisfied: tenacity>=6.2.0 in ./.venv/lib/python3.12/site-packages (from plotly==5.17.0->-r requirements.txt (line 6)) (9.1.4)
Requirement already satisfied: altair<6,>=4.0 in ./.venv/lib/python3.12/site-packages (from streamlit==1.40.2->-r requirements.txt (line 7)) (5.5.0)
Requirement already satisfied: blinker<2,>=1.0.0 in ./.venv/lib/python3.12/site-packages (from streamlit==1.40.2->-r requirements.txt (line 7)) (1.9.0)
Requirement already satisfied: cachetools<6,>=4.0 in ./.venv/lib/python3.12/site-packages (from streamlit==1.40.2->-r requirements.txt (line 7)) (5.5.2)
Requirement already satisfied: click<9,>=7.0 in ./.venv/lib/python3.12/site-packages (from streamlit==1.40.2->-r requirements.txt (line 7)) (8.3.1)
Requirement already satisfied: protobuf<6,>=3.20 in ./.venv/lib/python3.12/site-packages (from streamlit==1.40.2->-r requirements.txt (line 7)) (5.29.6)
Requirement already satisfied: pyarrow>=7.0 in ./.venv/lib/python3.12/site-packages (from streamlit==1.40.2->-r requirements.txt (line 7)) (23.0.1)
Requirement already satisfied: rich<14,>=10.14.0 in ./.venv/lib/python3.12/site-packages (from streamlit==1.40.2->-r requirements.txt (line 7)) (13.9.4)
Requirement already satisfied: toml<2,>=0.10.1 in ./.venv/lib/python3.12/site-packages (from streamlit==1.40.2->-r requirements.txt (line 7)) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.3.0 in ./.venv/lib/python3.12/site-packages (from streamlit==1.40.2->-r requirements.txt (line 7)) (4.15.0)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in ./.venv/lib/python3.12/site-packages (from streamlit==1.40.2->-r requirements.txt (line 7)) (3.1.46)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in ./.venv/lib/python3.12/site-packages (from streamlit==1.40.2->-r requirements.txt (line 7)) (0.9.1)
Requirement already satisfied: tornado<7,>=6.0.3 in ./.venv/lib/python3.12/site-packages (from streamlit==1.40.2->-r requirements.txt (line 7)) (6.5.5)
Requirement already satisfied: joblib>=1.1.1 in ./.venv/lib/python3.12/site-packages (from imbalanced-learn==0.11.0->-r requirements.txt (line 9)) (1.5.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in ./.venv/lib/python3.12/site-packages (from imbalanced-learn==0.11.0->-r requirements.txt (line 9)) (3.6.0)
Requirement already satisfied: PyWavelets in ./.venv/lib/python3.12/site-packages (from imagehash==4.3.1->ydata-profiling==4.12.0->-r requirements.txt (line 5)) (1.9.0)
Requirement already satisfied: jsonschema>=3.0 in ./.venv/lib/python3.12/site-packages (from altair<6,>=4.0->streamlit==1.40.2->-r requirements.txt (line 7)) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in ./.venv/lib/python3.12/site-packages (from altair<6,>=4.0->streamlit==1.40.2->-r requirements.txt (line 7)) (2.18.1)
Requirement already satisfied: gitdb<5,>=4.0.1 in ./.venv/lib/python3.12/site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit==1.40.2->-r requirements.txt (line 7)) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in ./.venv/lib/python3.12/site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit==1.40.2->-r requirements.txt (line 7)) (5.0.3)
Requirement already satisfied: MarkupSafe>=2.0 in ./.venv/lib/python3.12/site-packages (from jinja2<3.2,>=2.11.1->ydata-profiling==4.12.0->-r requirements.txt (line 5)) (3.0.3)
Requirement already satisfied: llvmlite<0.47,>=0.46.0dev0 in ./.venv/lib/python3.12/site-packages (from numba<1,>=0.56.0->ydata-profiling==4.12.0->-r requirements.txt (line 5)) (0.46.0)
Requirement already satisfied: charset_normalizer<4,>=2 in ./.venv/lib/python3.12/site-packages (from requests<3,>=2.24.0->ydata-profiling==4.12.0->-r requirements.txt (line 5)) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in ./.venv/lib/python3.12/site-packages (from requests<3,>=2.24.0->ydata-profiling==4.12.0->-r requirements.txt (line 5)) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./.venv/lib/python3.12/site-packages (from requests<3,>=2.24.0->ydata-profiling==4.12.0->-r requirements.txt (line 5)) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in ./.venv/lib/python3.12/site-packages (from requests<3,>=2.24.0->ydata-profiling==4.12.0->-r requirements.txt (line 5)) (2026.2.25)
Requirement already satisfied: markdown-it-py>=2.2.0 in ./.venv/lib/python3.12/site-packages (from rich<14,>=10.14.0->streamlit==1.40.2->-r requirements.txt (line 7)) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in ./.venv/lib/python3.12/site-packages (from rich<14,>=10.14.0->streamlit==1.40.2->-r requirements.txt (line 7)) (2.19.2)
Requirement already satisfied: patsy>=0.5.6 in ./.venv/lib/python3.12/site-packages (from statsmodels<1,>=0.13.2->ydata-profiling==4.12.0->-r requirements.txt (line 5)) (1.0.2)
Requirement already satisfied: attrs>=19.3.0 in ./.venv/lib/python3.12/site-packages (from visions<0.7.7,>=0.7.5->visions[type_image_path]<0.7.7,>=0.7.5->ydata-profiling==4.12.0->-r requirements.txt (line 5)) (26.1.0)
Requirement already satisfied: networkx>=2.4 in ./.venv/lib/python3.12/site-packages (from visions<0.7.7,>=0.7.5->visions[type_image_path]<0.7.7,>=0.7.5->ydata-profiling==4.12.0->-r requirements.txt (line 5)) (3.6.1)
Requirement already satisfied: et-xmlfile in ./.venv/lib/python3.12/site-packages (from openpyxl->-r requirements.txt (line 14)) (2.0.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in ./.venv/lib/python3.12/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit==1.40.2->-r requirements.txt (line 7)) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in ./.venv/lib/python3.12/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit==1.40.2->-r requirements.txt (line 7)) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in ./.venv/lib/python3.12/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit==1.40.2->-r requirements.txt (line 7)) (0.30.0)
Requirement already satisfied: mdurl~=0.1 in ./.venv/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich<14,>=10.14.0->streamlit==1.40.2->-r requirements.txt (line 7)) (0.1.2)
Requirement already satisfied: annotated-types>=0.6.0 in ./.venv/lib/python3.12/site-packages (from pydantic>=2->ydata-profiling==4.12.0->-r requirements.txt (line 5)) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in ./.venv/lib/python3.12/site-packages (from pydantic>=2->ydata-profiling==4.12.0->-r requirements.txt (line 5)) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in ./.venv/lib/python3.12/site-packages (from pydantic>=2->ydata-profiling==4.12.0->-r requirements.txt (line 5)) (0.4.2)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas==2.1.1->-r requirements.txt (line 2)) (1.17.0)

# Import necessary libraries

In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

# Section 1 - Load Data

In this section, we load the raw transaction data from the source CSV file and prepare it as a DataFrame for analysis.

* Input: data/source/online_retail.csv
* Output: A raw DataFrame (df_raw) containing all transactions

In [7]:
df = pd.read_csv("data/source/online_retail.csv")
print(df.shape)

(541909, 8)

---

### Check Missing Data

In [8]:
df.isna().sum()

InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
CustomerID        0
Country           0
dtype: int64

In the cell above we can see that the description is missing for 1454 rows. Since we need product names 
for our analysis and not the description, we remove these rows.

In [9]:
df.dropna(subset=["Description"], inplace=True)
print(df.shape)

(540455, 8)

Checking for duplicates

In [14]:
print(df.duplicated().sum())
df[df.duplicated(keep=False)].sort_values(by="InvoiceNo")

5268

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
485,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,2010-12-01 11:45:00,4.95,17908,United Kingdom
489,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 11:45:00,2.10,17908,United Kingdom
494,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908,United Kingdom
517,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908,United Kingdom
521,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,2010-12-01 11:45:00,2.95,17908,United Kingdom
...,...,...,...,...,...,...,...,...
440149,C574510,22360,GLASS JAR ENGLISH CONFECTIONERY,-1,2011-11-04 13:25:00,2.95,15110,United Kingdom
461407,C575940,23309,SET OF 60 I LOVE LONDON CAKE CASES,-24,2011-11-13 11:38:00,0.55,17838,United Kingdom
461408,C575940,23309,SET OF 60 I LOVE LONDON CAKE CASES,-24,2011-11-13 11:38:00,0.55,17838,United Kingdom
529981,C580764,22667,RECIPE BOX RETROSPOT,-12,2011-12-06 10:38:00,2.95,14562,United Kingdom
529980,C580764,22667,RECIPE BOX RETROSPOT,-12,2011-12-06 10:38:00,2.95,14562,United Kingdom

Drop the identical duplicates

In [15]:
df = df.drop_duplicates()
print(df.shape)

(535187, 8)

Check for rows with zero or negative UnitPrice and remove

In [16]:
df = df[df["UnitPrice"] > 0]
print(df.shape)

(534129, 8)

Check for returns (negative quantity) and remove

Returns are identified by a negative Quantity value and are 
removed as we are only analysing completed purchases.

In [17]:
df = df[df["Quantity"] > 0]
print(df.shape)

(524878, 8)

Create a total price column

In [20]:
df["TotalPrice"] = df["UnitPrice"] * df["Quantity"]
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,Month,Year
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30,12,2010
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,12,2010
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00,12,2010
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,12,2010
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,12,2010

Converting InvoiceDate to DateTime

In [19]:
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])
df["Month"] = df["InvoiceDate"].dt.month
df["Year"] = df["InvoiceDate"].dt.year

df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,Month,Year
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30,12,2010
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,12,2010
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00,12,2010
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,12,2010
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,12,2010

Check the new columns

In [21]:
print(df.shape)
df.head()

(524878, 11)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,Month,Year
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30,12,2010
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,12,2010
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00,12,2010
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,12,2010
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,12,2010

---

Save the cleaned dataset to the output folder for use in the next notebook where we will analyse it.

In [22]:
df.to_csv("data/processed/online_retail_cleaned.csv", index=False)

Checking the cleaned csv file

In [23]:
df_cleaned = pd.read_csv("data/processed/online_retail_cleaned.csv")
print(df_cleaned.shape)
df_cleaned.head()

(524878, 11)

/var/folders/c0/b3t2bq595gxctk3zh1z0tr_h0000gn/T/ipykernel_76552/3109179276.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df_cleaned = pd.read_csv("data/processed/online_retail_cleaned.csv")

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,Month,Year
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30,12,2010
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,12,2010
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00,12,2010
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,12,2010
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,12,2010

In [24]:
print(df.shape)
print(df.isna().sum())
df.head()

(524878, 11)
InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
TotalPrice     0
Month          0
Year           0
dtype: int64

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,Month,Year
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30,12,2010
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,12,2010
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00,12,2010
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,12,2010
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,12,2010

NOTE

* You may add as many sections as you want, as long as it supports your project workflow.
* All notebook's cells should be run top-down (you can't create a dynamic wherein a given point you need to go back to a previous cell to execute some task, like go back to a previous cell and refresh a variable content)

---

# Push files to Repo

* In cases where you don't need to push files to Repo, you may replace this section with "Conclusions and Next Steps" and state your conclusions and next steps.

In [10]:
import os
try:
  # create your folder here
  # os.makedirs(name='')
except Exception as e:
  print(e)

IndentationError: expected an indented block after 'try' statement on line 2 (553063055.py, line 5)